### PR TITLE
jenkinsfile: integration tests run faster

### PR DESCRIPTION
**Pull request by palino**

### CODE REVIEW

**Comment by palino** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Comment by palino** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Comment by ppitonak** [comment]
test this

**Pull request closed without merging**
